name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  show-python-version:
    runs-on: ubuntu-latest
    steps:
      - name: Show Python Version
        run: python --version

  pylint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: python-3.12.0-alpha.5-linux-18.04-x64.tar.gz
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: .
      - name: Run Pylint
        run: |
          pip install pylint
          pylint app.py
        working-directory: .
